[CmdletBinding()]
param(
    [string]$CheckoutRoot = "E:\ptc3527-benchmark\webrtc-checkout",
    [string]$DepotTools = "E:\ptc3527-benchmark\depot_tools",
    [string]$CacheRoot = (Join-Path $HOME ".cache\ptc3527-benchmark")
)

$ErrorActionPreference = "Stop"
$sourceCommit = "eb79ac6e330baa0a6d26c53d522f9ed57495edb7"
$depotToolsCommit = "30e761311cf7529a8b6b16233da46af5d26fba02"
$sourceRoot = Join-Path $CheckoutRoot "src"
$generatedRoot = Join-Path $sourceRoot "tools\ptc3527_apm_ns"
$buildRoot = Join-Path $sourceRoot "out\ptc3527_apm_ns"
$rootBuildFile = Join-Path $sourceRoot "BUILD.gn"
$outputDir = Join-Path $CacheRoot "bin"
$output = Join-Path $outputDir "ptc3527-webrtc-apm-ns.exe"
$wrapper = Join-Path $PSScriptRoot "webrtc_apm_ns_adapter.cc"
$buildFile = Join-Path $PSScriptRoot "webrtc_apm_ns_BUILD.gn"

if (-not (Test-Path (Join-Path $sourceRoot ".git"))) {
    throw "Checkout WebRTC nao encontrado em $sourceRoot"
}
if (-not (Test-Path (Join-Path $DepotTools ".git"))) {
    throw "depot_tools nao encontrado em $DepotTools"
}
$actualSourceCommit = (git -C $sourceRoot rev-parse HEAD).Trim()
if ($actualSourceCommit -ne $sourceCommit) {
    throw "Commit WebRTC inesperado: $actualSourceCommit"
}
$actualDepotToolsCommit = (git -C $DepotTools rev-parse HEAD).Trim()
if ($actualDepotToolsCommit -ne $depotToolsCommit) {
    throw "Commit depot_tools inesperado: $actualDepotToolsCommit"
}

New-Item -ItemType Directory -Force -Path $generatedRoot, $outputDir | Out-Null
Copy-Item -LiteralPath $wrapper -Destination (
    Join-Path $generatedRoot "webrtc_apm_ns_adapter.cc"
) -Force
Copy-Item -LiteralPath $buildFile -Destination (
    Join-Path $generatedRoot "BUILD.gn"
) -Force

$rootBuildBytes = [System.IO.File]::ReadAllBytes($rootBuildFile)
$rootBuildText = [System.Text.Encoding]::UTF8.GetString($rootBuildBytes)
$rootBuildAddition = @"

# Temporary entry point generated by Build-WebRTCAPMAdapter.ps1.
group("ptc3527_apm_ns_build") {
  deps = [ "//tools/ptc3527_apm_ns:ptc3527_webrtc_apm_ns_adapter" ]
}
"@
[System.IO.File]::WriteAllText(
    $rootBuildFile,
    $rootBuildText + $rootBuildAddition,
    [System.Text.UTF8Encoding]::new($false)
)

$env:PATH = "$DepotTools;$env:PATH"
$env:DEPOT_TOOLS_UPDATE = "0"
$env:DEPOT_TOOLS_WIN_TOOLCHAIN = "0"

Push-Location $sourceRoot
try {
    $gnArgs = 'is_debug=false rtc_include_tests=false rtc_build_examples=false is_component_build=false target_cpu=\"x64\"'
    gn gen $buildRoot "--args=$gnArgs"
    if ($LASTEXITCODE -ne 0) {
        throw "gn gen falhou com codigo $LASTEXITCODE"
    }
    autoninja -C $buildRoot ptc3527_apm_ns_build
    if ($LASTEXITCODE -ne 0) {
        throw "Build WebRTC APM falhou com codigo $LASTEXITCODE"
    }
}
finally {
    Pop-Location
    [System.IO.File]::WriteAllBytes($rootBuildFile, $rootBuildBytes)
}

$built = Join-Path $buildRoot "ptc3527_webrtc_apm_ns_adapter.exe"
if (-not (Test-Path $built)) {
    throw "Executavel compilado nao encontrado em $built"
}
Copy-Item -LiteralPath $built -Destination $output -Force

[ordered]@{
    source_commit = $actualSourceCommit
    depot_tools_commit = $actualDepotToolsCommit
    configuration = "release-x64; NS default moderate; other APM modules disabled"
    executable = $output
    executable_sha256 = (Get-FileHash $output -Algorithm SHA256).Hash
} | ConvertTo-Json
